configuration: Release

before_build:
  - nuget restore
  
install:
  - ps: powershell .\before_build.ps1

build:
  verbosity: minimal

artifacts:
  - path: Ducode.Local\bin\$(configuration)
    name: dotlocal