configuration: Release

before_build:
  - nuget restore
  
install:
  - ps: Write-Host 'This is PowerShell'

build:
  verbosity: minimal

artifacts:
  - path: Ducode.Local\bin\$(configuration)
    name: dotlocal