configuration: Release

before_build:
  - nuget restore
  
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "0.1.0.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

build:
  verbosity: minimal

after_build:
  - ps: powershell .\AfterBuild.ps1

artifacts:
  - path: Ducode.Local\bin\$(configuration)
    name: dotlocal