//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ducode.Local.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ducode.Local.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic authentication is enabled..
        /// </summary>
        public static string basic_auth_enabled {
            get {
                return ResourceManager.GetString("basic_auth_enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (c) Duco Winterwerp - ducode.org
        ///Icon by Icons Land (www.icons-land.com).
        /// </summary>
        public static string copyright {
            get {
                return ResourceManager.GetString("copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default file is &quot;{0}&quot;.
        /// </summary>
        public static string default_file {
            get {
                return ResourceManager.GetString("default_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory listing is disabled.
        /// </summary>
        public static string directory_listing_disabled {
            get {
                return ResourceManager.GetString("directory_listing_disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory listing is enabled.
        /// </summary>
        public static string directory_listing_enabled {
            get {
                return ResourceManager.GetString("directory_listing_enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DotLocal - Version {0}.
        /// </summary>
        public static string dotlocal {
            get {
                return ResourceManager.GetString("dotlocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     _        _______  _______  _______  _       
        ///   ( \      (  ___  )(  ____ \(  ___  )( \      
        ///   | (      | (   ) || (    \/| (   ) || (      
        ///   | |      | |   | || |      | (___) || |      
        ///   | |      | |   | || |      |  ___  || |      
        ///   | |      | |   | || |      | (   ) || |      
        /// _ | (____/\| (___) || (____/\| )   ( || (____/\
        ///(_)(_______/(_______)(_______/|/     \|(_______/.
        /// </summary>
        public static string dotlocal_letters {
            get {
                return ResourceManager.GetString("dotlocal_letters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to use basic authentication, provide both a username and password..
        /// </summary>
        public static string fill_in_username_and_password {
            get {
                return ResourceManager.GetString("fill_in_username_and_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listening at port {0}.
        /// </summary>
        public static string listening_at_port {
            get {
                return ResourceManager.GetString("listening_at_port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging is disabled.
        /// </summary>
        public static string logging_disabled {
            get {
                return ResourceManager.GetString("logging_disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging is enabled.
        /// </summary>
        public static string logging_enabled {
            get {
                return ResourceManager.GetString("logging_enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port {0} is already in use....
        /// </summary>
        public static string port_in_use {
            get {
                return ResourceManager.GetString("port_in_use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to exit....
        /// </summary>
        public static string press_any_key {
            get {
                return ResourceManager.GetString("press_any_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://*:{0}/.
        /// </summary>
        public static string url_format {
            get {
                return ResourceManager.GetString("url_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The web server root folder is &quot;{0}&quot;.
        /// </summary>
        public static string web_server_root {
            get {
                return ResourceManager.GetString("web_server_root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The web server root folder &quot;{0}&quot; doesn&apos;t exist..
        /// </summary>
        public static string web_server_root_invalid {
            get {
                return ResourceManager.GetString("web_server_root_invalid", resourceCulture);
            }
        }
    }
}
